server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <client_id>
            client-secret: <secret_key>
          github:
            client-id: <client_id>
            client-secret: <secret_key>


jwt:
  secretKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  access-duration: 3600  # in second
  refreshable-duration: 86400 # in seconds
app:
  services:
    profile: "http://localhost:8081/profile"
  frontend:
    resetPasswordUri:  "http://localhost:8080/change-password?token="
    magicLinkUri: "http://localhost:8080/magic-link?token="
    verifyAccountUri: "http://localhost:8080/verify-account?token="
  topic:
    welcomEmail: welcomEmail-notifcation
    resetPasswordLink: resetPasswordLink-notifcation
    magicLoginLink: magicLoginLink-notifcation
    verifyAccountLink: verifyAccountLink-notifcation